// This file is auto-generated by @hey-api/openapi-ts

/**
 * DashboardBase
 */
export type DashboardBase = {
    /**
     * Events Count
     */
    events_count?: number | null;
    /**
     * Tasks Count
     */
    tasks_count?: number | null;
    /**
     * Notes Count
     */
    notes_count?: number | null;
};

/**
 * Event
 */
export type Event = {
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Date From
     */
    date_from?: string | null;
    /**
     * Date To
     */
    date_to?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: number;
    event_type?: EventType | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Updated On
     */
    updated_on?: string;
    /**
     * Created On
     */
    created_on?: string;
};

/**
 * EventCreate
 */
export type EventCreate = {
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Date From
     */
    date_from?: string | null;
    /**
     * Date To
     */
    date_to?: string | null;
};

/**
 * EventType
 */
export type EventType = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Emoji
     */
    emoji?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Updated On
     */
    updated_on: string;
    /**
     * Created On
     */
    created_on: string;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Current Event Id
     */
    current_event_id?: number | null;
    /**
     * Current Event Duration
     */
    current_event_duration?: number | null;
    /**
     * Current Event Description
     */
    current_event_description?: string | null;
    /**
     * Current Record Id
     */
    current_record_id?: number | null;
    /**
     * Current Record Date From
     */
    current_record_date_from?: string | null;
    /**
     * Events Number
     */
    events_number?: number | null;
    /**
     * Current Event
     */
    current_event?: string | null;
};

/**
 * EventTypeCreate
 */
export type EventTypeCreate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Emoji
     */
    emoji?: string | null;
};

/**
 * EventTypeDelete
 */
export type EventTypeDelete = {
    /**
     * New Event Type Id
     */
    new_event_type_id?: number | null;
};

/**
 * EventTypeUpdate
 */
export type EventTypeUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Emoji
     */
    emoji?: string | null;
};

/**
 * EventUpdate
 */
export type EventUpdate = {
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Date From
     */
    date_from?: string | null;
    /**
     * Date To
     */
    date_to?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * GroupOut
 */
export type GroupOut = {
    /**
     * Date
     */
    date: string;
    /**
     * Data
     */
    data: Array<Event>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Note
 */
export type Note = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Additional Tag
     */
    additional_tag?: string | null;
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
    /**
     * Images
     */
    images?: Array<string> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Updated On
     */
    updated_on: string;
    /**
     * Created On
     */
    created_on: string;
};

/**
 * NoteCreate
 */
export type NoteCreate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Additional Tag
     */
    additional_tag?: string | null;
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
    /**
     * Images
     */
    images?: Array<string> | null;
};

/**
 * NoteUpdate
 */
export type NoteUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Additional Tag
     */
    additional_tag?: string | null;
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
    /**
     * Images
     */
    images?: Array<string> | null;
};

/**
 * PaginationSchema[EventType]
 */
export type PaginationSchemaEventType = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Items
     */
    items: Array<EventType>;
};

/**
 * PaginationSchema[Event]
 */
export type PaginationSchemaEvent = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Items
     */
    items: Array<Event>;
};

/**
 * PaginationSchema[GroupOut]
 */
export type PaginationSchemaGroupOut = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Items
     */
    items: Array<GroupOut>;
};

/**
 * PaginationSchema[Note]
 */
export type PaginationSchemaNote = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Items
     */
    items: Array<Note>;
};

/**
 * PaginationSchema[Task]
 */
export type PaginationSchemaTask = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Items
     */
    items: Array<Task>;
};

/**
 * Task
 */
export type Task = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Is Completed
     */
    is_completed?: boolean | null;
    /**
     * Is Accepted
     */
    is_accepted?: boolean | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Additional Tag
     */
    additional_tag?: string | null;
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Updated On
     */
    updated_on: string;
    /**
     * Created On
     */
    created_on: string;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Is Completed
     */
    is_completed?: boolean | null;
    /**
     * Is Accepted
     */
    is_accepted?: boolean | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Additional Tag
     */
    additional_tag?: string | null;
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Is Completed
     */
    is_completed?: boolean | null;
    /**
     * Is Accepted
     */
    is_accepted?: boolean | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Additional Tag
     */
    additional_tag?: string | null;
    /**
     * Event Type Id
     */
    event_type_id?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadEventTypesApiV1EventTypesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Order By
         */
        order_by?: string;
        /**
         * Order
         */
        order?: string;
        /**
         * Duration
         */
        duration?: number;
        /**
         * Is Tasks
         */
        is_tasks?: boolean;
        /**
         * Is Notes
         */
        is_notes?: boolean;
        /**
         * Search
         */
        search?: string;
    };
    url: '/api/v1/event-types/';
};

export type ReadEventTypesApiV1EventTypesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEventTypesApiV1EventTypesGetError = ReadEventTypesApiV1EventTypesGetErrors[keyof ReadEventTypesApiV1EventTypesGetErrors];

export type ReadEventTypesApiV1EventTypesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchemaEventType;
};

export type ReadEventTypesApiV1EventTypesGetResponse = ReadEventTypesApiV1EventTypesGetResponses[keyof ReadEventTypesApiV1EventTypesGetResponses];

export type CreateNewEventTypeApiV1EventTypesPostData = {
    body: EventTypeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/event-types/';
};

export type CreateNewEventTypeApiV1EventTypesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewEventTypeApiV1EventTypesPostError = CreateNewEventTypeApiV1EventTypesPostErrors[keyof CreateNewEventTypeApiV1EventTypesPostErrors];

export type CreateNewEventTypeApiV1EventTypesPostResponses = {
    /**
     * Successful Response
     */
    200: EventType;
};

export type CreateNewEventTypeApiV1EventTypesPostResponse = CreateNewEventTypeApiV1EventTypesPostResponses[keyof CreateNewEventTypeApiV1EventTypesPostResponses];

export type DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteData = {
    body: EventTypeDelete;
    path: {
        /**
         * Event Type Id
         */
        event_type_id: number;
    };
    query?: never;
    url: '/api/v1/event-types/{event_type_id}/';
};

export type DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteError = DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteErrors[keyof DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteErrors];

export type DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: EventType;
};

export type DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteResponse = DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteResponses[keyof DeleteExistingEventTypeApiV1EventTypesEventTypeIdDeleteResponses];

export type ReadEventTypeApiV1EventTypesEventTypeIdGetData = {
    body?: never;
    path: {
        /**
         * Event Type Id
         */
        event_type_id: number;
    };
    query?: never;
    url: '/api/v1/event-types/{event_type_id}/';
};

export type ReadEventTypeApiV1EventTypesEventTypeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEventTypeApiV1EventTypesEventTypeIdGetError = ReadEventTypeApiV1EventTypesEventTypeIdGetErrors[keyof ReadEventTypeApiV1EventTypesEventTypeIdGetErrors];

export type ReadEventTypeApiV1EventTypesEventTypeIdGetResponses = {
    /**
     * Successful Response
     */
    200: EventType;
};

export type ReadEventTypeApiV1EventTypesEventTypeIdGetResponse = ReadEventTypeApiV1EventTypesEventTypeIdGetResponses[keyof ReadEventTypeApiV1EventTypesEventTypeIdGetResponses];

export type UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutData = {
    body: EventTypeUpdate;
    path: {
        /**
         * Event Type Id
         */
        event_type_id: number;
    };
    query?: never;
    url: '/api/v1/event-types/{event_type_id}/';
};

export type UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutError = UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutErrors[keyof UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutErrors];

export type UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutResponses = {
    /**
     * Successful Response
     */
    200: EventType;
};

export type UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutResponse = UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutResponses[keyof UpdateExistingEventTypeApiV1EventTypesEventTypeIdPutResponses];

export type ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Event Type Id
         */
        event_type_id: number;
    };
    query?: never;
    url: '/api/v1/event-types/{event_type_id}/events/';
};

export type ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetError = ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetErrors[keyof ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetErrors];

export type ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchemaGroupOut;
};

export type ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetResponse = ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetResponses[keyof ReadEventTypeEventsApiV1EventTypesEventTypeIdEventsGetResponses];

export type ReadEventsApiV1EventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Event Type Id
         */
        event_type_id?: number;
    };
    url: '/api/v1/events/';
};

export type ReadEventsApiV1EventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEventsApiV1EventsGetError = ReadEventsApiV1EventsGetErrors[keyof ReadEventsApiV1EventsGetErrors];

export type ReadEventsApiV1EventsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchemaEvent;
};

export type ReadEventsApiV1EventsGetResponse = ReadEventsApiV1EventsGetResponses[keyof ReadEventsApiV1EventsGetResponses];

export type CreateNewEventApiV1EventsPostData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/api/v1/events/';
};

export type CreateNewEventApiV1EventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewEventApiV1EventsPostError = CreateNewEventApiV1EventsPostErrors[keyof CreateNewEventApiV1EventsPostErrors];

export type CreateNewEventApiV1EventsPostResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type CreateNewEventApiV1EventsPostResponse = CreateNewEventApiV1EventsPostResponses[keyof CreateNewEventApiV1EventsPostResponses];

export type DeleteExistingEventApiV1EventsEventIdDeleteData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/api/v1/events/{event_id}/';
};

export type DeleteExistingEventApiV1EventsEventIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExistingEventApiV1EventsEventIdDeleteError = DeleteExistingEventApiV1EventsEventIdDeleteErrors[keyof DeleteExistingEventApiV1EventsEventIdDeleteErrors];

export type DeleteExistingEventApiV1EventsEventIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type DeleteExistingEventApiV1EventsEventIdDeleteResponse = DeleteExistingEventApiV1EventsEventIdDeleteResponses[keyof DeleteExistingEventApiV1EventsEventIdDeleteResponses];

export type ReadEventApiV1EventsEventIdGetData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/api/v1/events/{event_id}/';
};

export type ReadEventApiV1EventsEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEventApiV1EventsEventIdGetError = ReadEventApiV1EventsEventIdGetErrors[keyof ReadEventApiV1EventsEventIdGetErrors];

export type ReadEventApiV1EventsEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type ReadEventApiV1EventsEventIdGetResponse = ReadEventApiV1EventsEventIdGetResponses[keyof ReadEventApiV1EventsEventIdGetResponses];

export type UpdateExistingEventApiV1EventsEventIdPutData = {
    body: EventUpdate;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/api/v1/events/{event_id}/';
};

export type UpdateExistingEventApiV1EventsEventIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateExistingEventApiV1EventsEventIdPutError = UpdateExistingEventApiV1EventsEventIdPutErrors[keyof UpdateExistingEventApiV1EventsEventIdPutErrors];

export type UpdateExistingEventApiV1EventsEventIdPutResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type UpdateExistingEventApiV1EventsEventIdPutResponse = UpdateExistingEventApiV1EventsEventIdPutResponses[keyof UpdateExistingEventApiV1EventsEventIdPutResponses];

export type PauseEventApiV1EventsPauseEventIdPostData = {
    body: EventUpdate;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/api/v1/events/pause/{event_id}/';
};

export type PauseEventApiV1EventsPauseEventIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseEventApiV1EventsPauseEventIdPostError = PauseEventApiV1EventsPauseEventIdPostErrors[keyof PauseEventApiV1EventsPauseEventIdPostErrors];

export type PauseEventApiV1EventsPauseEventIdPostResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type PauseEventApiV1EventsPauseEventIdPostResponse = PauseEventApiV1EventsPauseEventIdPostResponses[keyof PauseEventApiV1EventsPauseEventIdPostResponses];

export type StopEventApiV1EventsStopEventIdPostData = {
    body: EventUpdate;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/api/v1/events/stop/{event_id}/';
};

export type StopEventApiV1EventsStopEventIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopEventApiV1EventsStopEventIdPostError = StopEventApiV1EventsStopEventIdPostErrors[keyof StopEventApiV1EventsStopEventIdPostErrors];

export type StopEventApiV1EventsStopEventIdPostResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type StopEventApiV1EventsStopEventIdPostResponse = StopEventApiV1EventsStopEventIdPostResponses[keyof StopEventApiV1EventsStopEventIdPostResponses];

export type ContinueEventApiV1EventsContinueEventIdPostData = {
    body: EventUpdate;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/api/v1/events/continue/{event_id}/';
};

export type ContinueEventApiV1EventsContinueEventIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContinueEventApiV1EventsContinueEventIdPostError = ContinueEventApiV1EventsContinueEventIdPostErrors[keyof ContinueEventApiV1EventsContinueEventIdPostErrors];

export type ContinueEventApiV1EventsContinueEventIdPostResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type ContinueEventApiV1EventsContinueEventIdPostResponse = ContinueEventApiV1EventsContinueEventIdPostResponses[keyof ContinueEventApiV1EventsContinueEventIdPostResponses];

export type ReadTasksApiV1TasksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Order By
         */
        order_by?: string;
        /**
         * Order
         */
        order?: string;
        /**
         * Is Completed
         */
        is_completed?: boolean;
        /**
         * Is Deadline
         */
        is_deadline?: boolean;
        /**
         * Search
         */
        search?: string;
        /**
         * Event Type Id
         */
        event_type_id?: number;
    };
    url: '/api/v1/tasks/';
};

export type ReadTasksApiV1TasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTasksApiV1TasksGetError = ReadTasksApiV1TasksGetErrors[keyof ReadTasksApiV1TasksGetErrors];

export type ReadTasksApiV1TasksGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchemaTask;
};

export type ReadTasksApiV1TasksGetResponse = ReadTasksApiV1TasksGetResponses[keyof ReadTasksApiV1TasksGetResponses];

export type CreateNewTaskApiV1TasksPostData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tasks/';
};

export type CreateNewTaskApiV1TasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewTaskApiV1TasksPostError = CreateNewTaskApiV1TasksPostErrors[keyof CreateNewTaskApiV1TasksPostErrors];

export type CreateNewTaskApiV1TasksPostResponses = {
    /**
     * Successful Response
     */
    200: Task;
};

export type CreateNewTaskApiV1TasksPostResponse = CreateNewTaskApiV1TasksPostResponses[keyof CreateNewTaskApiV1TasksPostResponses];

export type DeleteExistingTaskApiV1TasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/';
};

export type DeleteExistingTaskApiV1TasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExistingTaskApiV1TasksTaskIdDeleteError = DeleteExistingTaskApiV1TasksTaskIdDeleteErrors[keyof DeleteExistingTaskApiV1TasksTaskIdDeleteErrors];

export type DeleteExistingTaskApiV1TasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Task;
};

export type DeleteExistingTaskApiV1TasksTaskIdDeleteResponse = DeleteExistingTaskApiV1TasksTaskIdDeleteResponses[keyof DeleteExistingTaskApiV1TasksTaskIdDeleteResponses];

export type ReadTaskApiV1TasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/';
};

export type ReadTaskApiV1TasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskApiV1TasksTaskIdGetError = ReadTaskApiV1TasksTaskIdGetErrors[keyof ReadTaskApiV1TasksTaskIdGetErrors];

export type ReadTaskApiV1TasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: Task;
};

export type ReadTaskApiV1TasksTaskIdGetResponse = ReadTaskApiV1TasksTaskIdGetResponses[keyof ReadTaskApiV1TasksTaskIdGetResponses];

export type UpdateExistingTaskApiV1TasksTaskIdPutData = {
    body: TaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/';
};

export type UpdateExistingTaskApiV1TasksTaskIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateExistingTaskApiV1TasksTaskIdPutError = UpdateExistingTaskApiV1TasksTaskIdPutErrors[keyof UpdateExistingTaskApiV1TasksTaskIdPutErrors];

export type UpdateExistingTaskApiV1TasksTaskIdPutResponses = {
    /**
     * Successful Response
     */
    200: Task;
};

export type UpdateExistingTaskApiV1TasksTaskIdPutResponse = UpdateExistingTaskApiV1TasksTaskIdPutResponses[keyof UpdateExistingTaskApiV1TasksTaskIdPutResponses];

export type ReadNotesApiV1NotesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Event Type Id
         */
        event_type_id?: number;
        /**
         * Order By
         */
        order_by?: string;
        /**
         * Order
         */
        order?: string;
        /**
         * Is Attachements
         */
        is_attachements?: boolean;
        /**
         * Title
         */
        title?: string;
        /**
         * Search
         */
        search?: string;
    };
    url: '/api/v1/notes/';
};

export type ReadNotesApiV1NotesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadNotesApiV1NotesGetError = ReadNotesApiV1NotesGetErrors[keyof ReadNotesApiV1NotesGetErrors];

export type ReadNotesApiV1NotesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchemaNote;
};

export type ReadNotesApiV1NotesGetResponse = ReadNotesApiV1NotesGetResponses[keyof ReadNotesApiV1NotesGetResponses];

export type CreateNewNoteApiV1NotesPostData = {
    body: NoteCreate;
    path?: never;
    query?: never;
    url: '/api/v1/notes/';
};

export type CreateNewNoteApiV1NotesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewNoteApiV1NotesPostError = CreateNewNoteApiV1NotesPostErrors[keyof CreateNewNoteApiV1NotesPostErrors];

export type CreateNewNoteApiV1NotesPostResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type CreateNewNoteApiV1NotesPostResponse = CreateNewNoteApiV1NotesPostResponses[keyof CreateNewNoteApiV1NotesPostResponses];

export type DeleteExistingNoteApiV1NotesNoteIdDeleteData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}/';
};

export type DeleteExistingNoteApiV1NotesNoteIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExistingNoteApiV1NotesNoteIdDeleteError = DeleteExistingNoteApiV1NotesNoteIdDeleteErrors[keyof DeleteExistingNoteApiV1NotesNoteIdDeleteErrors];

export type DeleteExistingNoteApiV1NotesNoteIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type DeleteExistingNoteApiV1NotesNoteIdDeleteResponse = DeleteExistingNoteApiV1NotesNoteIdDeleteResponses[keyof DeleteExistingNoteApiV1NotesNoteIdDeleteResponses];

export type ReadNoteApiV1NotesNoteIdGetData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}/';
};

export type ReadNoteApiV1NotesNoteIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadNoteApiV1NotesNoteIdGetError = ReadNoteApiV1NotesNoteIdGetErrors[keyof ReadNoteApiV1NotesNoteIdGetErrors];

export type ReadNoteApiV1NotesNoteIdGetResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type ReadNoteApiV1NotesNoteIdGetResponse = ReadNoteApiV1NotesNoteIdGetResponses[keyof ReadNoteApiV1NotesNoteIdGetResponses];

export type UpdateExistingNoteApiV1NotesNoteIdPutData = {
    body: NoteUpdate;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}/';
};

export type UpdateExistingNoteApiV1NotesNoteIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateExistingNoteApiV1NotesNoteIdPutError = UpdateExistingNoteApiV1NotesNoteIdPutErrors[keyof UpdateExistingNoteApiV1NotesNoteIdPutErrors];

export type UpdateExistingNoteApiV1NotesNoteIdPutResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type UpdateExistingNoteApiV1NotesNoteIdPutResponse = UpdateExistingNoteApiV1NotesNoteIdPutResponses[keyof UpdateExistingNoteApiV1NotesNoteIdPutResponses];

export type ReadTotalDashboardApiV1DashboardGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Event Type Id
         */
        event_type_id?: number;
    };
    url: '/api/v1/dashboard/';
};

export type ReadTotalDashboardApiV1DashboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTotalDashboardApiV1DashboardGetError = ReadTotalDashboardApiV1DashboardGetErrors[keyof ReadTotalDashboardApiV1DashboardGetErrors];

export type ReadTotalDashboardApiV1DashboardGetResponses = {
    /**
     * Successful Response
     */
    200: DashboardBase;
};

export type ReadTotalDashboardApiV1DashboardGetResponse = ReadTotalDashboardApiV1DashboardGetResponses[keyof ReadTotalDashboardApiV1DashboardGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8001' | (string & {});
};