require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '18.0'


# Подготовка проекта React Native
prepare_react_native_project!
use_frameworks! :linkage => :static
use_modular_headers! 

ENV['RCT_USE_PREBUILT_RNCORE'] = '0'

target 'Oseredok' do
  # Автоматически подключает нативные модули из package.json
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,      # можно false, если не хочешь Hermes
    :new_arch_enabled => false,
    :fabric_enabled => false
  )
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'RNFBApp',       :path => '../node_modules/@react-native-firebase/app'
  # pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  # НИЧЕГО лишнего сюда не добавляем: ни RNVectorIcons, ни GoogleUtilities и т.п.
  # Всё тянется через автолинкинг.

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    # Универсальные настройки для всех таргетов
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |cfg|
        cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
        cfg.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end