// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { UploadFileApiV1ImagesUploadPostData, UploadFileApiV1ImagesUploadPostResponses, UploadFileApiV1ImagesUploadPostErrors, DeleteFileApiV1ImagesFilenameDeleteData, DeleteFileApiV1ImagesFilenameDeleteResponses, DeleteFileApiV1ImagesFilenameDeleteErrors, GetFileApiV1ImagesFilenameGetData, GetFileApiV1ImagesFilenameGetResponses, GetFileApiV1ImagesFilenameGetErrors, UploadFileApiV1UserAvatarsUploadPostData, UploadFileApiV1UserAvatarsUploadPostResponses, UploadFileApiV1UserAvatarsUploadPostErrors, GetFileApiV1UserAvatarsUserIdFilenameGetData, GetFileApiV1UserAvatarsUserIdFilenameGetResponses, GetFileApiV1UserAvatarsUserIdFilenameGetErrors, DeleteFileApiV1UserAvatarsFilenameDeleteData, DeleteFileApiV1UserAvatarsFilenameDeleteResponses, DeleteFileApiV1UserAvatarsFilenameDeleteErrors, RootGetData, RootGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload File
 */
export const uploadFileApiV1ImagesUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadFileApiV1ImagesUploadPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UploadFileApiV1ImagesUploadPostResponses, UploadFileApiV1ImagesUploadPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/images/upload/',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Delete File
 */
export const deleteFileApiV1ImagesFilenameDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteFileApiV1ImagesFilenameDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteFileApiV1ImagesFilenameDeleteResponses, DeleteFileApiV1ImagesFilenameDeleteErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/images/{filename}/',
        ...options
    });
};

/**
 * Get File
 */
export const getFileApiV1ImagesFilenameGet = <ThrowOnError extends boolean = false>(options: Options<GetFileApiV1ImagesFilenameGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetFileApiV1ImagesFilenameGetResponses, GetFileApiV1ImagesFilenameGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/images/{filename}/',
        ...options
    });
};

/**
 * Upload File
 */
export const uploadFileApiV1UserAvatarsUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadFileApiV1UserAvatarsUploadPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UploadFileApiV1UserAvatarsUploadPostResponses, UploadFileApiV1UserAvatarsUploadPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/user-avatars/upload/',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Get File
 */
export const getFileApiV1UserAvatarsUserIdFilenameGet = <ThrowOnError extends boolean = false>(options: Options<GetFileApiV1UserAvatarsUserIdFilenameGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetFileApiV1UserAvatarsUserIdFilenameGetResponses, GetFileApiV1UserAvatarsUserIdFilenameGetErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/user-avatars/{user_id}/{filename}/',
        ...options
    });
};

/**
 * Delete File
 */
export const deleteFileApiV1UserAvatarsFilenameDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteFileApiV1UserAvatarsFilenameDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteFileApiV1UserAvatarsFilenameDeleteResponses, DeleteFileApiV1UserAvatarsFilenameDeleteErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/user-avatars/{filename}/',
        ...options
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<RootGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/',
        ...options
    });
};