// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_upload_file_api_v1_images_upload__post
 */
export type BodyUploadFileApiV1ImagesUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_file_api_v1_user_avatars_upload__post
 */
export type BodyUploadFileApiV1UserAvatarsUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageUploadResponse
 */
export type ImageUploadResponse = {
    /**
     * Filename
     */
    filename: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type UploadFileApiV1ImagesUploadPostData = {
    body: BodyUploadFileApiV1ImagesUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/images/upload/';
};

export type UploadFileApiV1ImagesUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileApiV1ImagesUploadPostError = UploadFileApiV1ImagesUploadPostErrors[keyof UploadFileApiV1ImagesUploadPostErrors];

export type UploadFileApiV1ImagesUploadPostResponses = {
    /**
     * Successful Response
     */
    201: ImageUploadResponse;
};

export type UploadFileApiV1ImagesUploadPostResponse = UploadFileApiV1ImagesUploadPostResponses[keyof UploadFileApiV1ImagesUploadPostResponses];

export type DeleteFileApiV1ImagesFilenameDeleteData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/v1/images/{filename}/';
};

export type DeleteFileApiV1ImagesFilenameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileApiV1ImagesFilenameDeleteError = DeleteFileApiV1ImagesFilenameDeleteErrors[keyof DeleteFileApiV1ImagesFilenameDeleteErrors];

export type DeleteFileApiV1ImagesFilenameDeleteResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetFileApiV1ImagesFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/v1/images/{filename}/';
};

export type GetFileApiV1ImagesFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileApiV1ImagesFilenameGetError = GetFileApiV1ImagesFilenameGetErrors[keyof GetFileApiV1ImagesFilenameGetErrors];

export type GetFileApiV1ImagesFilenameGetResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type UploadFileApiV1UserAvatarsUploadPostData = {
    body: BodyUploadFileApiV1UserAvatarsUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/user-avatars/upload/';
};

export type UploadFileApiV1UserAvatarsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileApiV1UserAvatarsUploadPostError = UploadFileApiV1UserAvatarsUploadPostErrors[keyof UploadFileApiV1UserAvatarsUploadPostErrors];

export type UploadFileApiV1UserAvatarsUploadPostResponses = {
    /**
     * Successful Response
     */
    201: ImageUploadResponse;
};

export type UploadFileApiV1UserAvatarsUploadPostResponse = UploadFileApiV1UserAvatarsUploadPostResponses[keyof UploadFileApiV1UserAvatarsUploadPostResponses];

export type GetFileApiV1UserAvatarsUserIdFilenameGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/v1/user-avatars/{user_id}/{filename}/';
};

export type GetFileApiV1UserAvatarsUserIdFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileApiV1UserAvatarsUserIdFilenameGetError = GetFileApiV1UserAvatarsUserIdFilenameGetErrors[keyof GetFileApiV1UserAvatarsUserIdFilenameGetErrors];

export type GetFileApiV1UserAvatarsUserIdFilenameGetResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteFileApiV1UserAvatarsFilenameDeleteData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/v1/user-avatars/{filename}/';
};

export type DeleteFileApiV1UserAvatarsFilenameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileApiV1UserAvatarsFilenameDeleteError = DeleteFileApiV1UserAvatarsFilenameDeleteErrors[keyof DeleteFileApiV1UserAvatarsFilenameDeleteErrors];

export type DeleteFileApiV1UserAvatarsFilenameDeleteResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8002' | (string & {});
};