// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * AccountOutSchema
 */
export type AccountOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Appartment Id
     */
    appartment_id: number;
    /**
     * Balance
     */
    balance: string;
};

/**
 * ApartmentCreateSchema
 */
export type ApartmentCreateSchema = {
    /**
     * Number
     */
    number: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Rooms
     */
    rooms: number;
    /**
     * Area
     */
    area: number;
    /**
     * Building Id
     */
    building_id?: number | null;
};

/**
 * ApartmentOutSchema
 */
export type ApartmentOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Number
     */
    number: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Rooms
     */
    rooms: number;
    /**
     * Area
     */
    area: number;
    /**
     * Building Id
     */
    building_id?: number | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ApartmentUpdateSchema
 */
export type ApartmentUpdateSchema = {
    /**
     * Number
     */
    number?: string | null;
    /**
     * Floor
     */
    floor?: number | null;
    /**
     * Rooms
     */
    rooms?: number | null;
    /**
     * Area
     */
    area?: number | null;
    /**
     * Building Id
     */
    building_id?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * BaseModel
 */
export type BaseModel = {
    [key: string]: unknown;
};

/**
 * Body_storage_save_api_v1_storage__post
 */
export type BodyStorageSaveApiV1StoragePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BuildingCreateSchema
 */
export type BuildingCreateSchema = {
    /**
     * Address
     */
    address: string;
    /**
     * City
     */
    city: string;
    /**
     * Postal Code
     */
    postal_code: string;
    /**
     * Country
     */
    country: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * BuildingOutSchema
 */
export type BuildingOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Address
     */
    address: string;
    /**
     * City
     */
    city: string;
    /**
     * Postal Code
     */
    postal_code: string;
    /**
     * Country
     */
    country: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created On
     */
    created_on?: string | null;
};

/**
 * BuildingUpdateSchema
 */
export type BuildingUpdateSchema = {
    /**
     * Address
     */
    address?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * BuildingUserRole
 */
export type BuildingUserRole = 'Resident' | 'BuildingManager' | 'SupportManager' | 'Accountant';

/**
 * ConfirmEmailSchema
 */
export type ConfirmEmailSchema = {
    /**
     * Email
     */
    email: string;
    /**
     * Code
     */
    code: string;
};

/**
 * DocumentCreateSchema
 */
export type DocumentCreateSchema = {
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * File Id
     */
    file_id?: string | null;
};

/**
 * DocumentOutSchema
 */
export type DocumentOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * File Id
     */
    file_id: string | null;
    /**
     * Created By Id
     */
    created_by_id: number | null;
    /**
     * Created At
     */
    created_at: string | null;
};

/**
 * DocumentUpdateSchema
 */
export type DocumentUpdateSchema = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * File Id
     */
    file_id?: string | null;
};

/**
 * EnvelopeCreateSchema
 */
export type EnvelopeCreateSchema = {
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Link
     */
    link: string;
};

/**
 * EnvelopeOutSchema
 */
export type EnvelopeOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Link
     */
    link: string;
    /**
     * Created By Id
     */
    created_by_id: number | null;
    /**
     * Created At
     */
    created_at: string | null;
};

/**
 * EnvelopeUpdateSchema
 */
export type EnvelopeUpdateSchema = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Link
     */
    link?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OfficeCreateSchema
 */
export type OfficeCreateSchema = {
    /**
     * Title
     */
    title: string;
    /**
     * Number
     */
    number: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Area
     */
    area: number;
    /**
     * Building Id
     */
    building_id?: number | null;
};

/**
 * OfficeOutSchema
 */
export type OfficeOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Number
     */
    number: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Area
     */
    area: number;
    /**
     * Building Id
     */
    building_id?: number | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * OfficeUpdateSchema
 */
export type OfficeUpdateSchema = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Number
     */
    number?: string | null;
    /**
     * Floor
     */
    floor?: number | null;
    /**
     * Area
     */
    area?: number | null;
    /**
     * Building Id
     */
    building_id?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * PaginationSchema
 */
export type PaginationSchema = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Items
     */
    items: Array<BaseModel>;
};

/**
 * PaymentInCreateSchema
 */
export type PaymentInCreateSchema = {
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * File Id
     */
    file_id?: string | null;
};

/**
 * PaymentInOutSchema
 */
export type PaymentInOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Description
     */
    description: string | null;
    /**
     * Amount
     */
    amount: string;
    /**
     * Is Approved
     */
    is_approved: boolean;
    /**
     * File Id
     */
    file_id: string | null;
    /**
     * Created By Id
     */
    created_by_id: number | null;
    /**
     * Created At
     */
    created_at: string | null;
};

/**
 * PaymentInUpdateSchema
 */
export type PaymentInUpdateSchema = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Amount
     */
    amount?: number | string | null;
    /**
     * Is Approved
     */
    is_approved?: boolean | null;
    /**
     * File Id
     */
    file_id?: string | null;
};

/**
 * PaymentOutCreateSchema
 */
export type PaymentOutCreateSchema = {
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Amount
     */
    amount: number | string;
};

/**
 * PaymentOutOutSchema
 */
export type PaymentOutOutSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Description
     */
    description: string | null;
    /**
     * Amount
     */
    amount: string;
    /**
     * Created By Id
     */
    created_by_id: number | null;
    /**
     * Created At
     */
    created_at: string | null;
};

/**
 * PaymentOutUpdateSchema
 */
export type PaymentOutUpdateSchema = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Amount
     */
    amount?: number | string | null;
};

/**
 * SendConfirmationCodeSchema
 */
export type SendConfirmationCodeSchema = {
    /**
     * Email
     */
    email: string;
};

/**
 * SetupBuildingSchema
 */
export type SetupBuildingSchema = {
    /**
     * Building Id
     */
    building_id: number;
    /**
     * Apartment Id
     */
    apartment_id: number;
    /**
     * Is Owner
     */
    is_owner?: boolean;
};

/**
 * StorageOutSchema
 */
export type StorageOutSchema = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * File Type
     */
    file_type: string;
    /**
     * Filename
     */
    filename: string;
};

/**
 * UserAddSchema
 */
export type UserAddSchema = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserInfo
 */
export type UserInfo = {
    /**
     * Id
     */
    id?: string | string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Notifications Enabled
     */
    is_notifications_enabled?: boolean | null;
    /**
     * Is Email Verified
     */
    is_email_verified?: boolean;
};

/**
 * UserLoginSchema
 */
export type UserLoginSchema = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Remember
     */
    remember?: boolean;
};

/**
 * UserOutSchema
 */
export type UserOutSchema = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: number;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Is Email Verified
     */
    is_email_verified?: boolean | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created On
     */
    created_on?: string | null;
    role?: BuildingUserRole | null;
    building?: BuildingOutSchema | null;
};

/**
 * UserOutWithTokenSchema
 */
export type UserOutWithTokenSchema = {
    user?: UserOutSchema | null;
    /**
     * Token
     */
    token?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Notifications Enabled
     */
    is_notifications_enabled?: boolean | null;
};

/**
 * UserUpdateSchema
 */
export type UserUpdateSchema = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Language
     */
    language?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterUserApiV1AuthSignupPostData = {
    body: UserAddSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup/';
};

export type RegisterUserApiV1AuthSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserApiV1AuthSignupPostError = RegisterUserApiV1AuthSignupPostErrors[keyof RegisterUserApiV1AuthSignupPostErrors];

export type RegisterUserApiV1AuthSignupPostResponses = {
    /**
     * Successful Response
     */
    201: UserOutWithTokenSchema;
};

export type RegisterUserApiV1AuthSignupPostResponse = RegisterUserApiV1AuthSignupPostResponses[keyof RegisterUserApiV1AuthSignupPostResponses];

export type SendConfirmationCodeApiV1AuthSendConfirmationCodePostData = {
    body: SendConfirmationCodeSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/send-confirmation-code/';
};

export type SendConfirmationCodeApiV1AuthSendConfirmationCodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendConfirmationCodeApiV1AuthSendConfirmationCodePostError = SendConfirmationCodeApiV1AuthSendConfirmationCodePostErrors[keyof SendConfirmationCodeApiV1AuthSendConfirmationCodePostErrors];

export type SendConfirmationCodeApiV1AuthSendConfirmationCodePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConfirmEmailApiV1AuthConfirmEmailPostData = {
    body: ConfirmEmailSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/confirm-email/';
};

export type ConfirmEmailApiV1AuthConfirmEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmEmailApiV1AuthConfirmEmailPostError = ConfirmEmailApiV1AuthConfirmEmailPostErrors[keyof ConfirmEmailApiV1AuthConfirmEmailPostErrors];

export type ConfirmEmailApiV1AuthConfirmEmailPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostLoginApiV1AuthSigninPostData = {
    body: UserLoginSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signin/';
};

export type PostLoginApiV1AuthSigninPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostLoginApiV1AuthSigninPostError = PostLoginApiV1AuthSigninPostErrors[keyof PostLoginApiV1AuthSigninPostErrors];

export type PostLoginApiV1AuthSigninPostResponses = {
    /**
     * Successful Response
     */
    200: UserOutWithTokenSchema;
};

export type PostLoginApiV1AuthSigninPostResponse = PostLoginApiV1AuthSigninPostResponses[keyof PostLoginApiV1AuthSigninPostResponses];

export type GetMeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/';
};

export type GetMeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserOutSchema;
};

export type GetMeApiV1AuthMeGetResponse = GetMeApiV1AuthMeGetResponses[keyof GetMeApiV1AuthMeGetResponses];

export type PatchMeApiV1AuthMePatchData = {
    body: UserUpdateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/';
};

export type PatchMeApiV1AuthMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchMeApiV1AuthMePatchError = PatchMeApiV1AuthMePatchErrors[keyof PatchMeApiV1AuthMePatchErrors];

export type PatchMeApiV1AuthMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserOutSchema;
};

export type PatchMeApiV1AuthMePatchResponse = PatchMeApiV1AuthMePatchResponses[keyof PatchMeApiV1AuthMePatchResponses];

export type SetupBuildingApiV1AuthSetupBuildingPostData = {
    body: SetupBuildingSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/setup-building/';
};

export type SetupBuildingApiV1AuthSetupBuildingPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetupBuildingApiV1AuthSetupBuildingPostError = SetupBuildingApiV1AuthSetupBuildingPostErrors[keyof SetupBuildingApiV1AuthSetupBuildingPostErrors];

export type SetupBuildingApiV1AuthSetupBuildingPostResponses = {
    /**
     * Successful Response
     */
    200: UserOutSchema;
};

export type SetupBuildingApiV1AuthSetupBuildingPostResponse = SetupBuildingApiV1AuthSetupBuildingPostResponses[keyof SetupBuildingApiV1AuthSetupBuildingPostResponses];

export type IsUserApiV1UsersIsUserGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         *
         * The UUID of the user to check
         */
        email: string;
    };
    url: '/api/v1/users/is-user/';
};

export type IsUserApiV1UsersIsUserGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IsUserApiV1UsersIsUserGetError = IsUserApiV1UsersIsUserGetErrors[keyof IsUserApiV1UsersIsUserGetErrors];

export type IsUserApiV1UsersIsUserGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangeUserApiV1UsersUserIdPatchData = {
    body?: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/';
};

export type ChangeUserApiV1UsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeUserApiV1UsersUserIdPatchError = ChangeUserApiV1UsersUserIdPatchErrors[keyof ChangeUserApiV1UsersUserIdPatchErrors];

export type ChangeUserApiV1UsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type ChangeUserApiV1UsersUserIdPatchResponse = ChangeUserApiV1UsersUserIdPatchResponses[keyof ChangeUserApiV1UsersUserIdPatchResponses];

export type IsUserApiV1UsersUserUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/user/{user_id}/';
};

export type IsUserApiV1UsersUserUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IsUserApiV1UsersUserUserIdGetError = IsUserApiV1UsersUserUserIdGetErrors[keyof IsUserApiV1UsersUserUserIdGetErrors];

export type IsUserApiV1UsersUserUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type IsUserApiV1UsersUserUserIdGetResponse = IsUserApiV1UsersUserUserIdGetResponses[keyof IsUserApiV1UsersUserUserIdGetResponses];

export type ListApartmentsApiV1AppartmentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * User Id
         */
        user_id?: number | null;
        /**
         * Building Id
         */
        building_id?: number | null;
    };
    url: '/api/v1/appartments/';
};

export type ListApartmentsApiV1AppartmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApartmentsApiV1AppartmentsGetError = ListApartmentsApiV1AppartmentsGetErrors[keyof ListApartmentsApiV1AppartmentsGetErrors];

export type ListApartmentsApiV1AppartmentsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchema;
};

export type ListApartmentsApiV1AppartmentsGetResponse = ListApartmentsApiV1AppartmentsGetResponses[keyof ListApartmentsApiV1AppartmentsGetResponses];

export type CreateApartmentApiV1AppartmentsPostData = {
    body: ApartmentCreateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/appartments/';
};

export type CreateApartmentApiV1AppartmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApartmentApiV1AppartmentsPostError = CreateApartmentApiV1AppartmentsPostErrors[keyof CreateApartmentApiV1AppartmentsPostErrors];

export type CreateApartmentApiV1AppartmentsPostResponses = {
    /**
     * Successful Response
     */
    201: ApartmentOutSchema;
};

export type CreateApartmentApiV1AppartmentsPostResponse = CreateApartmentApiV1AppartmentsPostResponses[keyof CreateApartmentApiV1AppartmentsPostResponses];

export type DeleteApartmentApiV1AppartmentsApartmentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Apartment Id
         */
        apartment_id: number;
    };
    query?: never;
    url: '/api/v1/appartments/{apartment_id}/';
};

export type DeleteApartmentApiV1AppartmentsApartmentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApartmentApiV1AppartmentsApartmentIdDeleteError = DeleteApartmentApiV1AppartmentsApartmentIdDeleteErrors[keyof DeleteApartmentApiV1AppartmentsApartmentIdDeleteErrors];

export type DeleteApartmentApiV1AppartmentsApartmentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApartmentApiV1AppartmentsApartmentIdDeleteResponse = DeleteApartmentApiV1AppartmentsApartmentIdDeleteResponses[keyof DeleteApartmentApiV1AppartmentsApartmentIdDeleteResponses];

export type GetApartmentApiV1AppartmentsApartmentIdGetData = {
    body?: never;
    path: {
        /**
         * Apartment Id
         */
        apartment_id: number;
    };
    query?: never;
    url: '/api/v1/appartments/{apartment_id}/';
};

export type GetApartmentApiV1AppartmentsApartmentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApartmentApiV1AppartmentsApartmentIdGetError = GetApartmentApiV1AppartmentsApartmentIdGetErrors[keyof GetApartmentApiV1AppartmentsApartmentIdGetErrors];

export type GetApartmentApiV1AppartmentsApartmentIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApartmentOutSchema;
};

export type GetApartmentApiV1AppartmentsApartmentIdGetResponse = GetApartmentApiV1AppartmentsApartmentIdGetResponses[keyof GetApartmentApiV1AppartmentsApartmentIdGetResponses];

export type UpdateApartmentApiV1AppartmentsApartmentIdPatchData = {
    body: ApartmentUpdateSchema;
    path: {
        /**
         * Apartment Id
         */
        apartment_id: number;
    };
    query?: never;
    url: '/api/v1/appartments/{apartment_id}/';
};

export type UpdateApartmentApiV1AppartmentsApartmentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApartmentApiV1AppartmentsApartmentIdPatchError = UpdateApartmentApiV1AppartmentsApartmentIdPatchErrors[keyof UpdateApartmentApiV1AppartmentsApartmentIdPatchErrors];

export type UpdateApartmentApiV1AppartmentsApartmentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ApartmentOutSchema;
};

export type UpdateApartmentApiV1AppartmentsApartmentIdPatchResponse = UpdateApartmentApiV1AppartmentsApartmentIdPatchResponses[keyof UpdateApartmentApiV1AppartmentsApartmentIdPatchResponses];

export type ListBuildingsApiV1BuildingsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
    };
    url: '/api/v1/buildings/';
};

export type ListBuildingsApiV1BuildingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBuildingsApiV1BuildingsGetError = ListBuildingsApiV1BuildingsGetErrors[keyof ListBuildingsApiV1BuildingsGetErrors];

export type ListBuildingsApiV1BuildingsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchema;
};

export type ListBuildingsApiV1BuildingsGetResponse = ListBuildingsApiV1BuildingsGetResponses[keyof ListBuildingsApiV1BuildingsGetResponses];

export type CreateBuildingApiV1BuildingsPostData = {
    body: BuildingCreateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/buildings/';
};

export type CreateBuildingApiV1BuildingsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBuildingApiV1BuildingsPostError = CreateBuildingApiV1BuildingsPostErrors[keyof CreateBuildingApiV1BuildingsPostErrors];

export type CreateBuildingApiV1BuildingsPostResponses = {
    /**
     * Successful Response
     */
    201: BuildingOutSchema;
};

export type CreateBuildingApiV1BuildingsPostResponse = CreateBuildingApiV1BuildingsPostResponses[keyof CreateBuildingApiV1BuildingsPostResponses];

export type DeleteBuildingApiV1BuildingsBuildingIdDeleteData = {
    body?: never;
    path: {
        /**
         * Building Id
         */
        building_id: number;
    };
    query?: never;
    url: '/api/v1/buildings/{building_id}/';
};

export type DeleteBuildingApiV1BuildingsBuildingIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBuildingApiV1BuildingsBuildingIdDeleteError = DeleteBuildingApiV1BuildingsBuildingIdDeleteErrors[keyof DeleteBuildingApiV1BuildingsBuildingIdDeleteErrors];

export type DeleteBuildingApiV1BuildingsBuildingIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteBuildingApiV1BuildingsBuildingIdDeleteResponse = DeleteBuildingApiV1BuildingsBuildingIdDeleteResponses[keyof DeleteBuildingApiV1BuildingsBuildingIdDeleteResponses];

export type GetBuildingApiV1BuildingsBuildingIdGetData = {
    body?: never;
    path: {
        /**
         * Building Id
         */
        building_id: number;
    };
    query?: never;
    url: '/api/v1/buildings/{building_id}/';
};

export type GetBuildingApiV1BuildingsBuildingIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBuildingApiV1BuildingsBuildingIdGetError = GetBuildingApiV1BuildingsBuildingIdGetErrors[keyof GetBuildingApiV1BuildingsBuildingIdGetErrors];

export type GetBuildingApiV1BuildingsBuildingIdGetResponses = {
    /**
     * Successful Response
     */
    200: BuildingOutSchema;
};

export type GetBuildingApiV1BuildingsBuildingIdGetResponse = GetBuildingApiV1BuildingsBuildingIdGetResponses[keyof GetBuildingApiV1BuildingsBuildingIdGetResponses];

export type UpdateBuildingApiV1BuildingsBuildingIdPatchData = {
    body: BuildingUpdateSchema;
    path: {
        /**
         * Building Id
         */
        building_id: number;
    };
    query?: never;
    url: '/api/v1/buildings/{building_id}/';
};

export type UpdateBuildingApiV1BuildingsBuildingIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBuildingApiV1BuildingsBuildingIdPatchError = UpdateBuildingApiV1BuildingsBuildingIdPatchErrors[keyof UpdateBuildingApiV1BuildingsBuildingIdPatchErrors];

export type UpdateBuildingApiV1BuildingsBuildingIdPatchResponses = {
    /**
     * Successful Response
     */
    200: BuildingOutSchema;
};

export type UpdateBuildingApiV1BuildingsBuildingIdPatchResponse = UpdateBuildingApiV1BuildingsBuildingIdPatchResponses[keyof UpdateBuildingApiV1BuildingsBuildingIdPatchResponses];

export type ListOfficesApiV1OfficesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
    };
    url: '/api/v1/offices/';
};

export type ListOfficesApiV1OfficesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOfficesApiV1OfficesGetError = ListOfficesApiV1OfficesGetErrors[keyof ListOfficesApiV1OfficesGetErrors];

export type ListOfficesApiV1OfficesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchema;
};

export type ListOfficesApiV1OfficesGetResponse = ListOfficesApiV1OfficesGetResponses[keyof ListOfficesApiV1OfficesGetResponses];

export type CreateOfficeApiV1OfficesPostData = {
    body: OfficeCreateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/offices/';
};

export type CreateOfficeApiV1OfficesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOfficeApiV1OfficesPostError = CreateOfficeApiV1OfficesPostErrors[keyof CreateOfficeApiV1OfficesPostErrors];

export type CreateOfficeApiV1OfficesPostResponses = {
    /**
     * Successful Response
     */
    201: OfficeOutSchema;
};

export type CreateOfficeApiV1OfficesPostResponse = CreateOfficeApiV1OfficesPostResponses[keyof CreateOfficeApiV1OfficesPostResponses];

export type DeleteOfficeApiV1OfficesOfficeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Office Id
         */
        office_id: number;
    };
    query?: never;
    url: '/api/v1/offices/{office_id}/';
};

export type DeleteOfficeApiV1OfficesOfficeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOfficeApiV1OfficesOfficeIdDeleteError = DeleteOfficeApiV1OfficesOfficeIdDeleteErrors[keyof DeleteOfficeApiV1OfficesOfficeIdDeleteErrors];

export type DeleteOfficeApiV1OfficesOfficeIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteOfficeApiV1OfficesOfficeIdDeleteResponse = DeleteOfficeApiV1OfficesOfficeIdDeleteResponses[keyof DeleteOfficeApiV1OfficesOfficeIdDeleteResponses];

export type GetOfficeApiV1OfficesOfficeIdGetData = {
    body?: never;
    path: {
        /**
         * Office Id
         */
        office_id: number;
    };
    query?: never;
    url: '/api/v1/offices/{office_id}/';
};

export type GetOfficeApiV1OfficesOfficeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOfficeApiV1OfficesOfficeIdGetError = GetOfficeApiV1OfficesOfficeIdGetErrors[keyof GetOfficeApiV1OfficesOfficeIdGetErrors];

export type GetOfficeApiV1OfficesOfficeIdGetResponses = {
    /**
     * Successful Response
     */
    200: OfficeOutSchema;
};

export type GetOfficeApiV1OfficesOfficeIdGetResponse = GetOfficeApiV1OfficesOfficeIdGetResponses[keyof GetOfficeApiV1OfficesOfficeIdGetResponses];

export type UpdateOfficeApiV1OfficesOfficeIdPatchData = {
    body: OfficeUpdateSchema;
    path: {
        /**
         * Office Id
         */
        office_id: number;
    };
    query?: never;
    url: '/api/v1/offices/{office_id}/';
};

export type UpdateOfficeApiV1OfficesOfficeIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOfficeApiV1OfficesOfficeIdPatchError = UpdateOfficeApiV1OfficesOfficeIdPatchErrors[keyof UpdateOfficeApiV1OfficesOfficeIdPatchErrors];

export type UpdateOfficeApiV1OfficesOfficeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: OfficeOutSchema;
};

export type UpdateOfficeApiV1OfficesOfficeIdPatchResponse = UpdateOfficeApiV1OfficesOfficeIdPatchResponses[keyof UpdateOfficeApiV1OfficesOfficeIdPatchResponses];

export type StorageSaveApiV1StoragePostData = {
    body: BodyStorageSaveApiV1StoragePost;
    path?: never;
    query?: never;
    url: '/api/v1/storage/';
};

export type StorageSaveApiV1StoragePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StorageSaveApiV1StoragePostError = StorageSaveApiV1StoragePostErrors[keyof StorageSaveApiV1StoragePostErrors];

export type StorageSaveApiV1StoragePostResponses = {
    /**
     * Successful Response
     */
    201: StorageOutSchema;
};

export type StorageSaveApiV1StoragePostResponse = StorageSaveApiV1StoragePostResponses[keyof StorageSaveApiV1StoragePostResponses];

export type StorageGetApiV1StorageUuidGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/api/v1/storage/{uuid}/';
};

export type StorageGetApiV1StorageUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StorageGetApiV1StorageUuidGetError = StorageGetApiV1StorageUuidGetErrors[keyof StorageGetApiV1StorageUuidGetErrors];

export type StorageGetApiV1StorageUuidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAccountApiV1FinanceAccountsAccountIdGetData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/v1/finance/accounts/{account_id}/';
};

export type GetAccountApiV1FinanceAccountsAccountIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAccountApiV1FinanceAccountsAccountIdGetError = GetAccountApiV1FinanceAccountsAccountIdGetErrors[keyof GetAccountApiV1FinanceAccountsAccountIdGetErrors];

export type GetAccountApiV1FinanceAccountsAccountIdGetResponses = {
    /**
     * Successful Response
     */
    200: AccountOutSchema;
};

export type GetAccountApiV1FinanceAccountsAccountIdGetResponse = GetAccountApiV1FinanceAccountsAccountIdGetResponses[keyof GetAccountApiV1FinanceAccountsAccountIdGetResponses];

export type GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetData = {
    body?: never;
    path: {
        /**
         * Appartment Id
         */
        appartment_id: number;
    };
    query?: never;
    url: '/api/v1/finance/accounts/by-appartment/{appartment_id}/';
};

export type GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetError = GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetErrors[keyof GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetErrors];

export type GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AccountOutSchema;
};

export type GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetResponse = GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetResponses[keyof GetAccountByAppartmentApiV1FinanceAccountsByAppartmentAppartmentIdGetResponses];

export type ListEnvelopesApiV1FinanceEnvelopesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Building Id
         */
        building_id?: number | null;
    };
    url: '/api/v1/finance/envelopes/';
};

export type ListEnvelopesApiV1FinanceEnvelopesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEnvelopesApiV1FinanceEnvelopesGetError = ListEnvelopesApiV1FinanceEnvelopesGetErrors[keyof ListEnvelopesApiV1FinanceEnvelopesGetErrors];

export type ListEnvelopesApiV1FinanceEnvelopesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchema;
};

export type ListEnvelopesApiV1FinanceEnvelopesGetResponse = ListEnvelopesApiV1FinanceEnvelopesGetResponses[keyof ListEnvelopesApiV1FinanceEnvelopesGetResponses];

export type CreateEnvelopeApiV1FinanceEnvelopesPostData = {
    body: EnvelopeCreateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/finance/envelopes/';
};

export type CreateEnvelopeApiV1FinanceEnvelopesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvelopeApiV1FinanceEnvelopesPostError = CreateEnvelopeApiV1FinanceEnvelopesPostErrors[keyof CreateEnvelopeApiV1FinanceEnvelopesPostErrors];

export type CreateEnvelopeApiV1FinanceEnvelopesPostResponses = {
    /**
     * Successful Response
     */
    201: EnvelopeOutSchema;
};

export type CreateEnvelopeApiV1FinanceEnvelopesPostResponse = CreateEnvelopeApiV1FinanceEnvelopesPostResponses[keyof CreateEnvelopeApiV1FinanceEnvelopesPostResponses];

export type DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Envelope Id
         */
        envelope_id: number;
    };
    query?: never;
    url: '/api/v1/finance/envelopes/{envelope_id}/';
};

export type DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteError = DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteErrors[keyof DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteErrors];

export type DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteResponse = DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteResponses[keyof DeleteEnvelopeApiV1FinanceEnvelopesEnvelopeIdDeleteResponses];

export type GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetData = {
    body?: never;
    path: {
        /**
         * Envelope Id
         */
        envelope_id: number;
    };
    query?: never;
    url: '/api/v1/finance/envelopes/{envelope_id}/';
};

export type GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetError = GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetErrors[keyof GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetErrors];

export type GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetResponses = {
    /**
     * Successful Response
     */
    200: EnvelopeOutSchema;
};

export type GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetResponse = GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetResponses[keyof GetEnvelopeApiV1FinanceEnvelopesEnvelopeIdGetResponses];

export type UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchData = {
    body: EnvelopeUpdateSchema;
    path: {
        /**
         * Envelope Id
         */
        envelope_id: number;
    };
    query?: never;
    url: '/api/v1/finance/envelopes/{envelope_id}/';
};

export type UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchError = UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchErrors[keyof UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchErrors];

export type UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: EnvelopeOutSchema;
};

export type UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchResponse = UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchResponses[keyof UpdateEnvelopeApiV1FinanceEnvelopesEnvelopeIdPatchResponses];

export type ListPaymentsInApiV1FinancePaymentsInGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Building Id
         */
        building_id?: number | null;
    };
    url: '/api/v1/finance/payments-in/';
};

export type ListPaymentsInApiV1FinancePaymentsInGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPaymentsInApiV1FinancePaymentsInGetError = ListPaymentsInApiV1FinancePaymentsInGetErrors[keyof ListPaymentsInApiV1FinancePaymentsInGetErrors];

export type ListPaymentsInApiV1FinancePaymentsInGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchema;
};

export type ListPaymentsInApiV1FinancePaymentsInGetResponse = ListPaymentsInApiV1FinancePaymentsInGetResponses[keyof ListPaymentsInApiV1FinancePaymentsInGetResponses];

export type CreatePaymentInApiV1FinancePaymentsInPostData = {
    body: PaymentInCreateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/finance/payments-in/';
};

export type CreatePaymentInApiV1FinancePaymentsInPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaymentInApiV1FinancePaymentsInPostError = CreatePaymentInApiV1FinancePaymentsInPostErrors[keyof CreatePaymentInApiV1FinancePaymentsInPostErrors];

export type CreatePaymentInApiV1FinancePaymentsInPostResponses = {
    /**
     * Successful Response
     */
    201: PaymentInOutSchema;
};

export type CreatePaymentInApiV1FinancePaymentsInPostResponse = CreatePaymentInApiV1FinancePaymentsInPostResponses[keyof CreatePaymentInApiV1FinancePaymentsInPostResponses];

export type DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: number;
    };
    query?: never;
    url: '/api/v1/finance/payments-in/{payment_id}/';
};

export type DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteError = DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteErrors[keyof DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteErrors];

export type DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteResponse = DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteResponses[keyof DeletePaymentInApiV1FinancePaymentsInPaymentIdDeleteResponses];

export type GetPaymentInApiV1FinancePaymentsInPaymentIdGetData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: number;
    };
    query?: never;
    url: '/api/v1/finance/payments-in/{payment_id}/';
};

export type GetPaymentInApiV1FinancePaymentsInPaymentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaymentInApiV1FinancePaymentsInPaymentIdGetError = GetPaymentInApiV1FinancePaymentsInPaymentIdGetErrors[keyof GetPaymentInApiV1FinancePaymentsInPaymentIdGetErrors];

export type GetPaymentInApiV1FinancePaymentsInPaymentIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaymentInOutSchema;
};

export type GetPaymentInApiV1FinancePaymentsInPaymentIdGetResponse = GetPaymentInApiV1FinancePaymentsInPaymentIdGetResponses[keyof GetPaymentInApiV1FinancePaymentsInPaymentIdGetResponses];

export type UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchData = {
    body: PaymentInUpdateSchema;
    path: {
        /**
         * Payment Id
         */
        payment_id: number;
    };
    query?: never;
    url: '/api/v1/finance/payments-in/{payment_id}/';
};

export type UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchError = UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchErrors[keyof UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchErrors];

export type UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PaymentInOutSchema;
};

export type UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchResponse = UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchResponses[keyof UpdatePaymentInApiV1FinancePaymentsInPaymentIdPatchResponses];

export type ListPaymentsOutApiV1FinancePaymentsOutGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Building Id
         */
        building_id?: number | null;
    };
    url: '/api/v1/finance/payments-out/';
};

export type ListPaymentsOutApiV1FinancePaymentsOutGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPaymentsOutApiV1FinancePaymentsOutGetError = ListPaymentsOutApiV1FinancePaymentsOutGetErrors[keyof ListPaymentsOutApiV1FinancePaymentsOutGetErrors];

export type ListPaymentsOutApiV1FinancePaymentsOutGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchema;
};

export type ListPaymentsOutApiV1FinancePaymentsOutGetResponse = ListPaymentsOutApiV1FinancePaymentsOutGetResponses[keyof ListPaymentsOutApiV1FinancePaymentsOutGetResponses];

export type CreatePaymentOutApiV1FinancePaymentsOutPostData = {
    body: PaymentOutCreateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/finance/payments-out/';
};

export type CreatePaymentOutApiV1FinancePaymentsOutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaymentOutApiV1FinancePaymentsOutPostError = CreatePaymentOutApiV1FinancePaymentsOutPostErrors[keyof CreatePaymentOutApiV1FinancePaymentsOutPostErrors];

export type CreatePaymentOutApiV1FinancePaymentsOutPostResponses = {
    /**
     * Successful Response
     */
    201: PaymentOutOutSchema;
};

export type CreatePaymentOutApiV1FinancePaymentsOutPostResponse = CreatePaymentOutApiV1FinancePaymentsOutPostResponses[keyof CreatePaymentOutApiV1FinancePaymentsOutPostResponses];

export type DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: number;
    };
    query?: never;
    url: '/api/v1/finance/payments-out/{payment_id}/';
};

export type DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteError = DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteErrors[keyof DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteErrors];

export type DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteResponse = DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteResponses[keyof DeletePaymentOutApiV1FinancePaymentsOutPaymentIdDeleteResponses];

export type GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: number;
    };
    query?: never;
    url: '/api/v1/finance/payments-out/{payment_id}/';
};

export type GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetError = GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetErrors[keyof GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetErrors];

export type GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaymentOutOutSchema;
};

export type GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetResponse = GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetResponses[keyof GetPaymentOutApiV1FinancePaymentsOutPaymentIdGetResponses];

export type UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchData = {
    body: PaymentOutUpdateSchema;
    path: {
        /**
         * Payment Id
         */
        payment_id: number;
    };
    query?: never;
    url: '/api/v1/finance/payments-out/{payment_id}/';
};

export type UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchError = UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchErrors[keyof UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchErrors];

export type UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PaymentOutOutSchema;
};

export type UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchResponse = UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchResponses[keyof UpdatePaymentOutApiV1FinancePaymentsOutPaymentIdPatchResponses];

export type ListDocumentsApiV1DocumentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Building Id
         */
        building_id?: number | null;
    };
    url: '/api/v1/documents/';
};

export type ListDocumentsApiV1DocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsApiV1DocumentsGetError = ListDocumentsApiV1DocumentsGetErrors[keyof ListDocumentsApiV1DocumentsGetErrors];

export type ListDocumentsApiV1DocumentsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginationSchema;
};

export type ListDocumentsApiV1DocumentsGetResponse = ListDocumentsApiV1DocumentsGetResponses[keyof ListDocumentsApiV1DocumentsGetResponses];

export type CreateDocumentApiV1DocumentsPostData = {
    body: DocumentCreateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/documents/';
};

export type CreateDocumentApiV1DocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDocumentApiV1DocumentsPostError = CreateDocumentApiV1DocumentsPostErrors[keyof CreateDocumentApiV1DocumentsPostErrors];

export type CreateDocumentApiV1DocumentsPostResponses = {
    /**
     * Successful Response
     */
    201: DocumentOutSchema;
};

export type CreateDocumentApiV1DocumentsPostResponse = CreateDocumentApiV1DocumentsPostResponses[keyof CreateDocumentApiV1DocumentsPostResponses];

export type DeleteDocumentApiV1DocumentsDocumentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: number;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/';
};

export type DeleteDocumentApiV1DocumentsDocumentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDocumentApiV1DocumentsDocumentIdDeleteError = DeleteDocumentApiV1DocumentsDocumentIdDeleteErrors[keyof DeleteDocumentApiV1DocumentsDocumentIdDeleteErrors];

export type DeleteDocumentApiV1DocumentsDocumentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDocumentApiV1DocumentsDocumentIdDeleteResponse = DeleteDocumentApiV1DocumentsDocumentIdDeleteResponses[keyof DeleteDocumentApiV1DocumentsDocumentIdDeleteResponses];

export type GetDocumentApiV1DocumentsDocumentIdGetData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: number;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/';
};

export type GetDocumentApiV1DocumentsDocumentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentApiV1DocumentsDocumentIdGetError = GetDocumentApiV1DocumentsDocumentIdGetErrors[keyof GetDocumentApiV1DocumentsDocumentIdGetErrors];

export type GetDocumentApiV1DocumentsDocumentIdGetResponses = {
    /**
     * Successful Response
     */
    200: DocumentOutSchema;
};

export type GetDocumentApiV1DocumentsDocumentIdGetResponse = GetDocumentApiV1DocumentsDocumentIdGetResponses[keyof GetDocumentApiV1DocumentsDocumentIdGetResponses];

export type UpdateDocumentApiV1DocumentsDocumentIdPatchData = {
    body: DocumentUpdateSchema;
    path: {
        /**
         * Document Id
         */
        document_id: number;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/';
};

export type UpdateDocumentApiV1DocumentsDocumentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDocumentApiV1DocumentsDocumentIdPatchError = UpdateDocumentApiV1DocumentsDocumentIdPatchErrors[keyof UpdateDocumentApiV1DocumentsDocumentIdPatchErrors];

export type UpdateDocumentApiV1DocumentsDocumentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: DocumentOutSchema;
};

export type UpdateDocumentApiV1DocumentsDocumentIdPatchResponse = UpdateDocumentApiV1DocumentsDocumentIdPatchResponses[keyof UpdateDocumentApiV1DocumentsDocumentIdPatchResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
