// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { SignupUserApiV1AuthSignupPostData, SignupUserApiV1AuthSignupPostResponses, SignupUserApiV1AuthSignupPostErrors, SigninUserApiV1AuthSigninPostData, SigninUserApiV1AuthSigninPostResponses, SigninUserApiV1AuthSigninPostErrors, GetMeApiV1AuthMeGetData, GetMeApiV1AuthMeGetResponses, ChangeMeApiV1AuthMePatchData, ChangeMeApiV1AuthMePatchResponses, ChangeMeApiV1AuthMePatchErrors, RefreshTokenApiV1AuthRefreshTokenPostData, RefreshTokenApiV1AuthRefreshTokenPostResponses, RefreshTokenApiV1AuthRefreshTokenPostErrors, IsUserApiV1UsersIsUserGetData, IsUserApiV1UsersIsUserGetResponses, IsUserApiV1UsersIsUserGetErrors, ChangeUserApiV1UsersUserIdPatchData, ChangeUserApiV1UsersUserIdPatchResponses, ChangeUserApiV1UsersUserIdPatchErrors, RootGetData, RootGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Signup User
 */
export const signupUserApiV1AuthSignupPost = <ThrowOnError extends boolean = false>(options?: Options<SignupUserApiV1AuthSignupPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SignupUserApiV1AuthSignupPostResponses, SignupUserApiV1AuthSignupPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/auth/signup/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Signin User
 */
export const signinUserApiV1AuthSigninPost = <ThrowOnError extends boolean = false>(options: Options<SigninUserApiV1AuthSigninPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SigninUserApiV1AuthSigninPostResponses, SigninUserApiV1AuthSigninPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/auth/signin/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Me
 */
export const getMeApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeApiV1AuthMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeApiV1AuthMeGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/auth/me/',
        ...options
    });
};

/**
 * Change Me
 */
export const changeMeApiV1AuthMePatch = <ThrowOnError extends boolean = false>(options: Options<ChangeMeApiV1AuthMePatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<ChangeMeApiV1AuthMePatchResponses, ChangeMeApiV1AuthMePatchErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/auth/me/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Refresh Token
 */
export const refreshTokenApiV1AuthRefreshTokenPost = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenApiV1AuthRefreshTokenPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RefreshTokenApiV1AuthRefreshTokenPostResponses, RefreshTokenApiV1AuthRefreshTokenPostErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/auth/refresh-token/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Is User
 */
export const isUserApiV1UsersIsUserGet = <ThrowOnError extends boolean = false>(options: Options<IsUserApiV1UsersIsUserGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<IsUserApiV1UsersIsUserGetResponses, IsUserApiV1UsersIsUserGetErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/users/is-user/',
        ...options
    });
};

/**
 * Change User
 */
export const changeUserApiV1UsersUserIdPatch = <ThrowOnError extends boolean = false>(options: Options<ChangeUserApiV1UsersUserIdPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<ChangeUserApiV1UsersUserIdPatchResponses, ChangeUserApiV1UsersUserIdPatchErrors, ThrowOnError>({
        responseType: 'json',
        url: '/api/v1/users/{user_id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<RootGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/',
        ...options
    });
};