// This file is auto-generated by @hey-api/openapi-ts

/**
 * AuthSignin
 */
export type AuthSignin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AuthSignup
 */
export type AuthSignup = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RefreshTokenRequest
 */
export type RefreshTokenRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * SignInUserInfo
 */
export type SignInUserInfo = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Id Token
     */
    id_token: string;
    user_info: UserInfo;
};

/**
 * UserInfo
 */
export type UserInfo = {
    /**
     * Id
     */
    id?: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Notifications Enabled
     */
    is_notifications_enabled?: boolean | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Is Email Verified
     */
    is_email_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Notifications Enabled
     */
    is_notifications_enabled?: boolean | null;
    /**
     * Language
     */
    language?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SignupUserApiV1AuthSignupPostData = {
    body?: AuthSignup;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup/';
};

export type SignupUserApiV1AuthSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupUserApiV1AuthSignupPostError = SignupUserApiV1AuthSignupPostErrors[keyof SignupUserApiV1AuthSignupPostErrors];

export type SignupUserApiV1AuthSignupPostResponses = {
    /**
     * Successful Response
     */
    201: SignInUserInfo;
};

export type SignupUserApiV1AuthSignupPostResponse = SignupUserApiV1AuthSignupPostResponses[keyof SignupUserApiV1AuthSignupPostResponses];

export type SigninUserApiV1AuthSigninPostData = {
    body: AuthSignin;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signin/';
};

export type SigninUserApiV1AuthSigninPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SigninUserApiV1AuthSigninPostError = SigninUserApiV1AuthSigninPostErrors[keyof SigninUserApiV1AuthSigninPostErrors];

export type SigninUserApiV1AuthSigninPostResponses = {
    /**
     * Successful Response
     */
    200: SignInUserInfo;
};

export type SigninUserApiV1AuthSigninPostResponse = SigninUserApiV1AuthSigninPostResponses[keyof SigninUserApiV1AuthSigninPostResponses];

export type GetMeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/';
};

export type GetMeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type GetMeApiV1AuthMeGetResponse = GetMeApiV1AuthMeGetResponses[keyof GetMeApiV1AuthMeGetResponses];

export type ChangeMeApiV1AuthMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/';
};

export type ChangeMeApiV1AuthMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeMeApiV1AuthMePatchError = ChangeMeApiV1AuthMePatchErrors[keyof ChangeMeApiV1AuthMePatchErrors];

export type ChangeMeApiV1AuthMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type ChangeMeApiV1AuthMePatchResponse = ChangeMeApiV1AuthMePatchResponses[keyof ChangeMeApiV1AuthMePatchResponses];

export type RefreshTokenApiV1AuthRefreshTokenPostData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh-token/';
};

export type RefreshTokenApiV1AuthRefreshTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokenApiV1AuthRefreshTokenPostError = RefreshTokenApiV1AuthRefreshTokenPostErrors[keyof RefreshTokenApiV1AuthRefreshTokenPostErrors];

export type RefreshTokenApiV1AuthRefreshTokenPostResponses = {
    /**
     * Successful Response
     */
    200: SignInUserInfo;
};

export type RefreshTokenApiV1AuthRefreshTokenPostResponse = RefreshTokenApiV1AuthRefreshTokenPostResponses[keyof RefreshTokenApiV1AuthRefreshTokenPostResponses];

export type IsUserApiV1UsersIsUserGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         * The UUID of the user to check
         */
        email: string;
    };
    url: '/api/v1/users/is-user/';
};

export type IsUserApiV1UsersIsUserGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IsUserApiV1UsersIsUserGetError = IsUserApiV1UsersIsUserGetErrors[keyof IsUserApiV1UsersIsUserGetErrors];

export type IsUserApiV1UsersIsUserGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangeUserApiV1UsersUserIdPatchData = {
    body?: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/';
};

export type ChangeUserApiV1UsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeUserApiV1UsersUserIdPatchError = ChangeUserApiV1UsersUserIdPatchErrors[keyof ChangeUserApiV1UsersUserIdPatchErrors];

export type ChangeUserApiV1UsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type ChangeUserApiV1UsersUserIdPatchResponse = ChangeUserApiV1UsersUserIdPatchResponses[keyof ChangeUserApiV1UsersUserIdPatchResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};